import type { ProjectVoiceMode } from '@/features/video-studio/lib/ai/voice-selection';
import type { VideoLength } from '@/features/video-studio/types/script';
import type { GenerationStatus } from '@/features/video-studio/lib/ai/generation-status';
import type {
  SoundEffectTag,
  EmotionTag,
} from './director-presets';

// ==================== Director Types ====================

// Storyboard-specific status
export type StoryboardStatus = 'idle' | 'generating' | 'preview' | 'splitting' | 'editing' | 'error';

export type { GenerationStatus } from '@/features/video-studio/lib/ai/generation-status';
// Alias for backward compatibility
export type VideoStatus = GenerationStatus;

export interface SceneProviderState {
  provider: 'googleflow';
  preferredCredentialId?: string;
  accountId?: string;
  ownerScopeId?: string;
  projectId?: string;
  mediaIdsByOwnerScope?: Record<string, string>;
}

// Split scene.
// Two-tier prompt design:
// 1. imagePrompt - static description for the first-frame image
// 2. videoPrompt - dynamic action/motion description for video generation
export interface SplitScene {
  id: number;
  // Scene name, e.g. Village School
  sceneName: string;
  // Scene location, e.g. Interior Classroom
  sceneLocation: string;
  
  // ========== First Frame / Start State ==========
  // First-frame image, either cropped from the storyboard or generated by AI
  imageDataUrl: string;
  // HTTP URL for the first-frame image, used by video-generation APIs
  imageHttpUrl: string | null;
  // Max Studio media ids for this start frame, scoped by JWT hash.
  // Provider-neutral generation metadata.
  imageProviderState?: SceneProviderState;
  videoProviderState?: SceneProviderState;
  width: number;
  height: number;
  // English first-frame image prompt used for image-generation APIs
  // Focus on composition, lighting, appearance, and starting pose
  imagePrompt: string;
  // First-frame generation status
  imageStatus: GenerationStatus;
  imageProgress: number; // 0-100
  imageError: string | null;

  // ========== Video Action / Movement ==========
  // English video prompt for video-generation APIs
  // Focus on action progression, camera movement, and atmosphere changes
  // No need to repeat detailed appearance because the first-frame image already provides it
  videoPrompt: string;
  // Spoken voice-over/narration text, appended to videoPrompt only by generation code when voice is enabled
  voiceOver?: string;
  // True when the user explicitly materialized voiceOver into videoPrompt for visibility/editing
  voiceOverSynced?: boolean;
  videoLength: VideoLength;
  // Video generation status
  videoStatus: GenerationStatus;
  videoProgress: number; // 0-100
  videoUrl: string | null;
  videoError: string | null;
  // Media-library reference used for dragging into the timeline
  videoMediaId: string | null;
  
  // ========== Characters ==========
  // Character-library selection used to keep character appearance consistent during video generation
  characterIds: string[];
  characterNames?: string[];
  // Character wardrobe variation mapping (charId -> variationId), falling back to the base portrait when omitted
  characterVariationMap?: Record<string, string>;
  // Emotion tags (optional)
  emotionTags?: EmotionTag[];
  
  // ========== Imported screenplay information (reference only) ==========
  // Dialogue / spoken lines used for dubbing and subtitles
  dialogue: string;
  // Sound-effect text imported from the screenplay
  soundEffectText: string;
  
  // ========== Video Parameters ==========
  // Ambient-sound description injected into prompts
  ambientSound: string;
  // Sound-effect tags injected into prompts (legacy field retained for compatibility)
  soundEffects: SoundEffectTag[];
  
  // ========== Audio switches (control whether audio fields are injected into the video prompt) ==========
  audioAmbientEnabled?: boolean;   // Ambient-audio toggle, defaults to true
  audioSfxEnabled?: boolean;       // Sound-effect toggle, defaults to true
  audioDialogueEnabled?: boolean;  // Dialogue toggle, defaults to true
  audioBgmEnabled?: boolean;       // Background-music toggle, defaults to false
  backgroundMusic?: string;        // Background-music description
  
  // ========== Shot position metadata ==========
  row: number;
  col: number;
  sourceRect: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  
  // ========== Scene-library linkage (used for reference images) ==========
  // Start-frame scene linkage
  sceneLibraryId?: string;           // Scene library id
  sceneReferenceImage?: string;      // Scene background reference image URL
  sceneMasterReferenceImage?: string; // Master scene reference image URL
  // 1-based source shot indexes used as image references.
  ref_image?: number[];
  
  // First-frame source (used for display and tracking)
  imageSource?: 'ai-generated' | 'upload' | 'storyboard';
  
  // ========== Episode scope ==========
  sourceShotId?: string;
  sourceShotIndex?: number;
  sourceEpisodeIndex?: number;   // Source episode index
  sourceEpisodeId?: string;      // Source episode id
}

export interface DirectorScreenplayDraft {
  prompt: string;
  selectedCharacterIds: string[];
  updatedAt: number;
}

export interface DirectorEditorPrefs {
  imageGenMode: 'single' | 'merged';
  frameMode: 'first' | 'last' | 'both';
  refStrategy: 'cluster' | 'minimal' | 'none';
  useExemplar: boolean;
  activeTab: 'editing';
  episodeViewScope: 'all' | 'episode';
}

// Per-project director data
export interface DirectorProjectData {
  // Storyboard state (new workflow)
  storyboardImage: string | null;
  storyboardImageMediaId: string | null;
  storyboardStatus: StoryboardStatus;
  storyboardError: string | null;
  splitScenes: SplitScene[];
  projectFolderId: string | null;
  storyboardConfig: {
    aspectRatio: '16:9' | '9:16';
    resolution: '2K' | '4K' | '1K';
    videoResolution: '480p' | '720p' | '1080p';
    sceneCount: number;
    storyPrompt: string;
    /** Persisted visual-style preset id, e.g. '2d_ghibli', for accurate reverse lookup */
    visualStyleId?: string;
    /** Style id used when the current shot data was last calibrated, so style switches know whether recalibration is needed */
    calibratedStyleId?: string;
    styleTokens?: string[];
    characterReferenceImages?: string[];
    characterDescriptions?: string[];
    voiceMode?: ProjectVoiceMode;
    narratorVoice?: string;
    videoGenerationMode?: 'image-to-video' | 'ref-to-video';
  };
  
  screenplayDraft: DirectorScreenplayDraft;
  editorPrefs: DirectorEditorPrefs;
}
