import assert from 'node:assert/strict';

async function main() {
  const memory = new Map();
  Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { getItem: (key: string) => memory.get(key) || null, setItem: (key: string, value: string) => memory.set(key, value) } });
  const events = new Set<(task: any) => void>();
  (globalThis as any).window = { googleFlowRuntime: { onStatus: () => () => {}, onTask: (fn: any) => { events.add(fn); return () => events.delete(fn); }, getStatus: async () => ({ credentials: [{ credentialId: 'real', email: 'actual@gmail.com' }] }) } };
  const { useCanvasStore } = require('./canvas-store') as typeof import('./canvas-store');
  const { runNodes, cancelSpace, runNode, cancelNode } = require('./runner') as typeof import('./runner');
  const api = useCanvasStore.getState();
  const id = api.createSpace('Run test');
  const a = api.addNode(id, 'imageGenerator', { x: 0, y: 0 }), b = api.addNode(id, 'imageGenerator', { x: 400, y: 0 });
  api.updateNode(id, a, { prompt: 'one' }); api.updateNode(id, b, { prompt: 'two' });
  api.connect(id, { source: a, target: b, targetHandle: 'refs' });
  let calls = 0;
  (globalThis as any).__canvasGenerate = async (input: any) => {
    calls++;
    for (const listener of events) listener({ taskId: input.taskId, kind: 'image', status: 'submitting', credentialId: 'real', submittedAt: Date.now() });
    return new Promise((resolve, reject) => {
      const timeout = setTimeout(() => resolve({ taskId: input.taskId, localUrl: `result-${calls}`, credentialId: 'real' }), 30);
      input.signal.addEventListener('abort', () => { clearTimeout(timeout); reject(new DOMException('Cancelled', 'AbortError')); }, { once: true });
    });
  };
  await runNodes(id, [a, b]); assert.equal(calls, 2, 'selected dependency runs once');
  assert.equal(useCanvasStore.getState().spaces[0].nodes[0].output?.accountEmail, 'actual@gmail.com');
  calls = 0;
  await Promise.all([runNode(id, a), runNode(id, a)]); assert.equal(calls, 1, 'simultaneous clicks share execution');
  calls = 0;
  const cancelled = runNodes(id, [a, b]); cancelSpace(id);
  await assert.rejects(cancelled, { name: 'AbortError' }); assert.ok(calls <= 1);
  assert.equal(useCanvasStore.getState().spaces[0].nodes.some((node) => node.status === 'running'), false);
  const stopped = runNode(id, a); cancelNode(a); await assert.rejects(stopped, { name: 'AbortError' });
  assert.equal(events.size, 0, 'runtime subscriptions cleaned up');
  const batchSpace = api.createSpace('Batch');
  const list = api.addNode(batchSpace, 'list', { x: 0, y: 0 });
  const image = api.addNode(batchSpace, 'imageGenerator', { x: 400, y: 0 });
  const edit = api.addNode(batchSpace, 'imageEdit', { x: 800, y: 0 });
  api.updateNode(batchSpace, list, { items: ['cat', 'dog', 'bird'] });
  api.updateNode(batchSpace, edit, { prompt: '' });
  api.connect(batchSpace, { source: list, target: image, targetHandle: 'prompt' });
  api.connect(batchSpace, { source: image, target: edit, targetHandle: 'refs' });
  calls = 0; await runNode(batchSpace, edit);
  assert.equal(calls, 3, 'only upstream generation calls AI');
  assert.equal((globalThis as any).__localEdits, 3, 'all three images are processed locally');
  const batchState = () => useCanvasStore.getState().spaces.find((space) => space.id === batchSpace)!;
  assert.equal(batchState().nodes.find((node) => node.id === image)?.batchOutputs?.length, 3);
  calls = 0; await runNode(batchSpace, edit); assert.equal(calls, 0, 'local editing reuses clean upstream without AI');
  assert.equal(batchState().nodes.find((node) => node.id === edit)?.batchOutputs?.length, 3);
  api.updateNode(batchSpace, edit, { imageEdit: { crop: true, x: 0, y: 0, width: 50, height: 100, ratio: 'free', chroma: false, color: '#00ff00', threshold: 80, softness: 40 } });
  assert.equal(batchState().nodes.find((node) => node.id === edit)?.stale, true, 'edit settings invalidate output');
  api.saveTemplate(batchSpace, [list, image, edit], 'Reusable');
  const template = useCanvasStore.getState().templates[0];
  const pasted = api.pasteNodes(batchSpace, template.nodes, template.edges, 80);
  assert.equal(pasted.length, 3);
  assert.equal(batchState().nodes.find((node) => node.id === pasted[1])?.batchOutputs, undefined, 'template does not reuse generated batch');
  calls = 0; const partial = runNode(batchSpace, image);
  setTimeout(() => cancelNode(image), 45);
  await assert.rejects(partial, { name: 'AbortError' });
  assert.equal(batchState().nodes.find((node) => node.id === image)?.stale, true, 'cancelled batch cannot be reused as complete');
  assert.ok(calls < 3);
  const named = api.createSpace('Named upload');
  const local = api.addNode(named, 'localImage', { x: 0, y: 0 });
  const target = api.addNode(named, 'imageGenerator', { x: 400, y: 0 });
  api.setLocalImage(named, local, 'brand.png');
  api.updateNode(named, local, { name: 'Brand Logo' });
  api.updateNode(named, target, { prompt: `Use @{${local}} on a poster` });
  let submitted: any;
  (globalThis as any).__canvasGenerate = async (input: any) => { submitted = input; return { taskId: input.taskId, localUrl: 'named-output' }; };
  await assert.rejects(runNode(named, target), /INPUT_REQUIRED/);
  assert.equal(typeof submitted, 'undefined', 'unconnected mention must not reach the provider');
  api.connect(named, { source: local, target, targetHandle: 'refs' });
  await runNode(named, target);
  assert.equal(submitted.references[0].source, 'brand.png');
  assert.equal(submitted.references[0].fileName, 'Brand Logo');
  assert.equal(submitted.prompt, 'Use Brand Logo (reference image 1) on a poster');
  api.updateNode(named, local, { name: 'New Logo' });
  await runNode(named, target); assert.equal(submitted.references[0].fileName, 'New Logo');
  const video = api.addNode(named, 'videoGenerator', { x: 800, y: 0 });
  api.updateNode(named, video, { prompt: 'animate', model: 'Gemini_Omni_Flash', videoDuration: 10 });
  api.connect(named, { source: local, target: video, targetHandle: 'end' });
  let videoInput: any;
  (globalThis as any).__canvasGenerateVideo = async (input: any) => { videoInput = input; return { taskId: input.taskId, videoUrl: 'movie.mp4' }; };
  const textVideo = api.addNode(named, 'videoGenerator', { x: 1000, y: 300 });
  api.updateNode(named, textVideo, { prompt: 'A cat runs through a garden', model: 'Gemini_Omni_Flash' });
  await runNode(named, textVideo);
  assert.equal(videoInput.startImageUrl, undefined, 'First accepts text-only video');
  assert.equal(videoInput.referenceImageUrls, undefined);
  api.updateNode(named, textVideo, { videoMode: 'ref' });
  await runNode(named, textVideo);
  assert.equal(videoInput.startImageUrl, undefined, 'Ref without images uses text-to-video');
  assert.equal(videoInput.referenceImageUrls, undefined);
  videoInput = undefined;
  await assert.rejects(runNode(named, video), /VIDEO_START_REQUIRED/);
  assert.equal(typeof videoInput, 'undefined', 'end-only input must fail before provider/upload');
  api.connect(named, { source: local, target: video, targetHandle: 'start' });
  await runNode(named, video);
  assert.equal(videoInput.length, 10); assert.equal(videoInput.startImageUrl, 'brand.png');
  assert.equal(videoInput.referenceImageUrls, undefined, 'First never submits reference mode');
  const uploadedVideo = api.addNode(named, 'videoGenerator', { x: 1000, y: 0 });
  api.updateNode(named, uploadedVideo, { prompt: 'animate', refs: ['uploaded.png', 'extra.png'] });
  await runNode(named, uploadedVideo);
  assert.equal(videoInput.startImageUrl, 'uploaded.png', 'First uses the first uploaded image');
  assert.equal(videoInput.referenceImageUrls, undefined);
  api.updateNode(named, uploadedVideo, { videoMode: 'ref' });
  await runNode(named, uploadedVideo);
  assert.deepEqual(videoInput.referenceImageUrls, ['uploaded.png', 'extra.png']);
  assert.equal(videoInput.startImageUrl, undefined);
  assert.equal(videoInput.endImageUrl, undefined);
  api.connect(named, { source: local, target: uploadedVideo, targetHandle: 'start' });
  await runNode(named, uploadedVideo);
  assert.deepEqual(videoInput.referenceImageUrls, ['uploaded.png', 'extra.png', 'brand.png']);
  api.updateNode(named, uploadedVideo, { refs: ['1.png', '2.png', '3.png'] });
  await assert.rejects(runNode(named, uploadedVideo), /VIDEO_REF_INPUT_INVALID/);
  api.updateNode(named, video, { model: 'Veo_3.1-Fast' });
  await runNode(named, video); assert.equal(videoInput.length, 8, 'unsupported duration resets for actual model');
  const grokVideo = api.addNode(named, 'videoGenerator', { x: 1200, y: 0 });
  api.updateNode(named, grokVideo, { prompt: 'A cat walking', model: 'Grok Imagine Video', grokCredentialId: 'grok-selected' });
  await runNode(named, grokVideo);
  assert.equal(videoInput.platform, 'grok', 'Grok model routes to Grok');
  assert.equal(videoInput.preferredCredentialId, 'grok-selected', 'Canvas forwards the chosen Grok account');
  assert.equal(videoInput.startImageUrl, undefined, 'Grok accepts text-only video');
  assert.equal(videoInput.length, 10, 'Grok uses a supported duration');
  api.updateNode(named, grokVideo, { model: '', prompt: 'A cat walking again' });
  (globalThis as any).__canvasVideoModel = 'Grok Imagine Video';
  await runNode(named, grokVideo);
  assert.equal(videoInput.platform, 'grok', 'Auto follows the configured Grok model');
  (globalThis as any).__canvasVideoModel = undefined;
  api.updateNode(named, grokVideo, { model: 'Grok Imagine Video', videoMode: 'ref' });
  await assert.rejects(runNode(named, grokVideo), /Grok không hỗ trợ chế độ ảnh tham chiếu/);
  const { videoDurations, videoDuration } = require('../lib/ai/video-duration');
  assert.deepEqual(videoDurations('Gemini Omni Flash'), [4, 6, 8, 10]);
  assert.deepEqual(videoDurations('Veo_3.1-Fast'), [4, 6, 8]);
  assert.equal(videoDuration('Veo_3.1-Lite', 6), 6, 'keep requested duration; runtime enforces Ultra eligibility');
  assert.equal(videoDuration('Gemini Omni Flash', 6), 6);
  assert.equal(videoDuration('Gemini Omni Flash'), 8);
  assert.deepEqual(videoDurations('Grok Imagine Video'), [6, 10, 15]);
  const exportSpace = api.createSpace('Output test');
  const exportImage = api.addNode(exportSpace, 'imageGenerator', { x: 0, y: 0 });
  const exportVideo = api.addNode(exportSpace, 'localVideo', { x: 0, y: 200 });
  const exportNode = api.addNode(exportSpace, 'output', { x: 300, y: 0 });
  api.connect(exportSpace, { source: exportImage, target: exportNode, targetHandle: 'images' });
  api.connect(exportSpace, { source: exportVideo, target: exportNode, targetHandle: 'videos' });
  const writes: any[] = [];
  (window as any).exportStorage = { writeFiles: async (payload: any) => { writes.push(payload); return { success: true }; } };
  const beforeExportCalls = calls;
  await assert.rejects(runNode(exportSpace, exportNode), /OUTPUT_FOLDER_REQUIRED/);
  assert.equal(calls, beforeExportCalls, 'folder preflight runs before upstream generation');
  api.updateNode(exportSpace, exportImage, { status: 'done', stale: false, output: { kind: 'image', url: 'data:image/png;base64,AQ==', model: '', createdAt: 1 } });
  api.updateNode(exportSpace, exportVideo, { status: 'done', stale: false, output: { kind: 'video', url: 'data:video/mp4;base64,Ag==', model: '', createdAt: 1 } });
  api.updateNode(exportSpace, exportNode, { outputDirectory: 'D:/exports' });
  await runNode(exportSpace, exportNode);
  assert.equal(writes.length, 2);
  assert.equal(calls, beforeExportCalls, 'export reuses existing media');
  const savedNode = useCanvasStore.getState().spaces.find((space) => space.id === exportSpace)!.nodes.find((node) => node.id === exportNode)!;
  assert.equal(savedNode.status, 'done');
  assert.equal(savedNode.savedFiles?.length, 2);
  const aiSpace = api.createSpace('AI');
  const aiInput = api.addNode(aiSpace, 'text', { x: 0, y: 0 });
  const ai = api.addNode(aiSpace, 'ai', { x: 300, y: 0 });
  api.updateNode(aiSpace, aiInput, { prompt: 'A cat on a roof' });
  api.updateNode(aiSpace, ai, { prompt: 'Write a short image prompt', aiAdapter: 'codex', model: 'test-model' });
  api.connect(aiSpace, { source: aiInput, target: ai, targetHandle: 'prompt' });
  let aiCalls = 0;
  (window as any).cliRuntime = { cancelTextTask: async () => ({}), runTextTask: async (input: any) => {
    aiCalls++;
    assert.equal(input.adapter, 'codex'); assert.equal(input.model, 'test-model');
    assert.ok(input.prompt.includes('A cat on a roof')); assert.equal(input.enableContentMcp, false);
    return { success: true, outputText: 'A cinematic cat on a rooftop.' };
  } };
  await runNode(aiSpace, ai);
  const { nodeValues } = require('./graph');
  let currentAiSpace = useCanvasStore.getState().spaces.find((space) => space.id === aiSpace)!;
  assert.deepEqual(nodeValues(currentAiSpace.nodes, currentAiSpace.edges, ai), ['A cinematic cat on a rooftop.']);
  const nextAi = api.addNode(aiSpace, 'ai', { x: 600, y: 0 });
  api.updateNode(aiSpace, nextAi, { prompt: 'Summarize', aiAdapter: 'codex', model: 'test-model' });
  api.connect(aiSpace, { source: ai, target: nextAi, targetHandle: 'prompt' });
  (window as any).cliRuntime.runTextTask = async (input: any) => { aiCalls++; assert.ok(input.prompt.includes('cinematic cat')); return { success: true, outputText: 'Cat.' }; };
  await runNode(aiSpace, nextAi);
  assert.equal(aiCalls, 2, 'reuse completed AI upstream');
  api.updateNode(aiSpace, aiInput, { prompt: 'A dog' });
  currentAiSpace = useCanvasStore.getState().spaces.find((space) => space.id === aiSpace)!;
  assert.equal(currentAiSpace.nodes.find((node) => node.id === ai)!.stale, true);
  assert.equal(currentAiSpace.nodes.find((node) => node.id === nextAi)!.stale, true);
  const aiImage = api.addNode(aiSpace, 'localImage', { x: 0, y: 300 });
  api.updateNode(aiSpace, aiImage, { status: 'done', output: { kind: 'image', url: 'data:image/png;base64,AQ==', model: '', createdAt: 1 } });
  api.connect(aiSpace, { source: aiImage, target: ai, targetHandle: 'refs' });
  (globalThis as any).FileReader = class {
    result = ''; onload?: () => void;
    async readAsDataURL(blob: Blob) { this.result = `data:${blob.type};base64,${Buffer.from(await blob.arrayBuffer()).toString('base64')}`; this.onload?.(); }
  };
  (window as any).cliRuntime.runTextTask = async (input: any) => {
    assert.deepEqual(input.images, ['data:image/png;base64,AQ==']);
    assert.ok(input.prompt.includes('A dog'));
    return { success: true, outputText: 'Image analyzed.' };
  };
  await runNode(aiSpace, ai);
  api.updateNode(aiSpace, ai, { prompt: 'Only this edited prompt', promptIsFinal: true });
  (window as any).cliRuntime.runTextTask = async (input: any) => {
    assert.equal(input.prompt, 'Only this edited prompt');
    assert.deepEqual(input.images, ['data:image/png;base64,AQ==']);
    return { success: true, outputText: 'Edited.' };
  };
  await runNode(aiSpace, ai);
  const { effectivePrompt } = require('./graph');
  const reuseSpace = api.createSpace('AI reuses displayed image');
  const ancestor = api.addNode(reuseSpace, 'imageGenerator', { x: 0, y: 0 });
  const displayed = api.addNode(reuseSpace, 'imageGenerator', { x: 300, y: 0 });
  const analyze = api.addNode(reuseSpace, 'ai', { x: 600, y: 0 });
  api.updateNode(reuseSpace, ancestor, { prompt: 'Do not regenerate this ancestor' });
  api.updateNode(reuseSpace, displayed, { prompt: 'Changed settings', stale: true, output: { kind: 'image', url: 'data:image/png;base64,Aw==', model: '', createdAt: 1 } });
  api.updateNode(reuseSpace, analyze, { prompt: 'Describe this image' });
  api.connect(reuseSpace, { source: ancestor, target: displayed, targetHandle: 'refs' });
  api.connect(reuseSpace, { source: displayed, target: analyze, targetHandle: 'refs' });
  let generations = 0, analyses = 0;
  (globalThis as any).__canvasGenerate = async (input: any) => {
    generations++;
    return { taskId: input.taskId, localUrl: 'data:image/png;base64,Aw==' };
  };
  (window as any).cliRuntime.runTextTask = async (input: any) => {
    analyses++;
    assert.deepEqual(input.images, ['data:image/png;base64,Aw==']);
    return { success: true, outputText: 'Existing image analyzed.' };
  };
  await runNode(reuseSpace, analyze);
  await runNode(reuseSpace, analyze);
  assert.equal(generations, 0, 'AI reuses stale image and does not visit its missing ancestor');
  assert.equal(analyses, 2, 'each click runs only the requested AI');
  api.updateNode(reuseSpace, displayed, { output: { kind: 'image', url: 'idb-image://missing', model: '', createdAt: 1 } });
  await assert.rejects(runNode(reuseSpace, analyze), /Không thể đọc hoặc tải ảnh đầu vào/);
  assert.equal(generations, 0, 'unreadable output must not trigger image generation');
  assert.equal(analyses, 2, 'unreadable image must not reach CLI');
  api.updateNode(reuseSpace, displayed, { output: undefined, batchOutputs: undefined });
  await runNode(reuseSpace, analyze);
  assert.equal(generations, 2, 'missing image still generates its required dependency chain');
  const edited = useCanvasStore.getState().spaces.find((space) => space.id === aiSpace)!.nodes.find((node) => node.id === ai)!;
  assert.equal(effectivePrompt({ ...edited, promptIsFinal: false, prompt: 'Extra' }, ['First', 'Second']), 'First\nSecond\nExtra');
  assert.equal(effectivePrompt({ ...edited, kind: 'imageGenerator' }, ['Ignored']), 'Only this edited prompt');
  assert.equal(effectivePrompt({ ...edited, kind: 'videoGenerator', prompt: '' }, ['Ignored']), '');
  const duplicateAi = api.duplicateNode(aiSpace, ai)!;
  assert.equal(useCanvasStore.getState().spaces.find((space) => space.id === aiSpace)!.nodes.find((node) => node.id === duplicateAi)!.textOutput, undefined);
  console.log('Selected execution, deduplication, account, cancellation, output/AI chains, image attachments and cleanup checks passed.');
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
