import assert from 'node:assert/strict';
import { canUpscaleImage4K, imageUpscaleOwner } from './image-upscale';

async function main() {
  const memory = new Map();
  Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { getItem: (key: string) => memory.get(key) || null, setItem: (key: string, value: string) => memory.set(key, value) } });
  const accounts: any[] = [{ ownerScopeId: 'owner', credentialId: 'credential', email: 'owner@gmail.com', state: 'ready', tier: 'PAYGATE_TIER_ONE' }];
  (globalThis as any).window = { googleFlowRuntime: { onStatus: () => () => {}, onTask: () => () => {}, getStatus: async () => ({ credentials: accounts }) } };
  const { useCanvasStore, getSpace } = require('./canvas-store');
  const { upscaleNodeImage, cancelNode, runNode } = require('./runner');
  const api = useCanvasStore.getState();
  const space = api.createSpace('Upscale');
  const node = api.addNode(space, 'imageGenerator', { x: 0, y: 0 });
  const child = api.addNode(space, 'imageGenerator', { x: 300, y: 0 });
  api.connect(space, { source: node, target: child, targetHandle: 'refs' });
  const original = { kind: 'image' as const, url: 'original.jpg', model: 'GEM_PIX_2', mediaId: 'image-id', accountEmail: 'owner@gmail.com', createdAt: 1 };
  const second = { ...original, url: 'second.jpg' };
  api.updateNode(space, node, { output: original, batchOutputs: [original, second], status: 'done', stale: false });
  api.updateNode(space, child, { output: { ...original, url: 'child.jpg' }, status: 'done', stale: false });
  assert.equal(imageUpscaleOwner(original, accounts, 'other-owner'), 'owner');
  assert.equal(imageUpscaleOwner(original, [], 'other-owner'), undefined, 'offline owner must not fall through to another account');
  assert.equal(canUpscaleImage4K(accounts[0], []), false);
  assert.equal(canUpscaleImage4K(accounts[0], ['owner']), true);
  let calls = 0;
  (globalThis as any).__canvasUpscale = async (input: any) => {
    calls++; assert.equal(input.ownerScopeId, 'owner'); assert.equal(input.resolution, '2K');
    return { taskId: input.taskId, localUrl: 'upscaled.jpg', ownerScopeId: 'owner', credentialId: 'credential' };
  };
  const pending = upscaleNodeImage(space, node, '2K');
  assert.equal(upscaleNodeImage(space, node, '2K'), pending, 'double click uses one request');
  await pending;
  const result = getSpace(space).nodes.find((item: any) => item.id === node);
  assert.equal(calls, 1);
  assert.equal(result.output.url, 'upscaled.jpg');
  assert.equal(result.output.upscaleResolution, '2K');
  assert.ok(result.outputs.some((item: any) => item.url === original.url), 'original remains in history');
  assert.deepEqual(result.batchOutputs.map((item: any) => item.url), ['upscaled.jpg', 'second.jpg']);
  assert.equal(getSpace(space).nodes.find((item: any) => item.id === child).stale, true);
  (globalThis as any).__canvasUpscale = async () => { throw new Error('upscale failed'); };
  await assert.rejects(upscaleNodeImage(space, node, '4K'), /upscale failed/);
  assert.equal(getSpace(space).nodes.find((item: any) => item.id === node).output.url, 'upscaled.jpg');
  (globalThis as any).__canvasUpscale = async () => { throw new Error('cancelled call should not submit'); };
  const cancelled = upscaleNodeImage(space, node, '4K'); cancelNode(node); await cancelled;
  assert.equal(getSpace(space).nodes.find((item: any) => item.id === node).status, 'done');
  api.updateNode(space, node, { output: original, status: 'done', stale: false, batchOutputs: [original, second] });
  api.updateNode(space, child, { status: 'done', stale: false });
  (globalThis as any).__canvasUpscale = async (input: any) => ({ taskId: input.taskId, localUrl: 'download-4k.jpg', ownerScopeId: 'owner' });
  let downloaded: any;
  await upscaleNodeImage(space, node, '4K', async (output: any) => { downloaded = output; });
  const exported = getSpace(space).nodes.find((item: any) => item.id === node);
  assert.equal(downloaded.url, 'download-4k.jpg');
  assert.equal(exported.output.url, original.url, 'download-only upscale keeps the current graph image');
  assert.deepEqual(exported.batchOutputs.map((item: any) => item.url), [original.url, second.url]);
  assert.equal(getSpace(space).nodes.find((item: any) => item.id === child).stale, false, 'downloading must not invalidate downstream nodes');
  assert.ok(exported.outputs.some((item: any) => item.upscaleSourceUrl === original.url && item.upscaleResolution === '4K'), 'download is cached for reuse');
  const upscale = api.addNode(space, 'imageUpscale', { x: 600, y: 0 });
  await assert.rejects(runNode(space, upscale), /nối ảnh Google Flow/);
  api.connect(space, { source: node, target: upscale, targetHandle: 'refs' });
  let graphCalls = 0;
  (globalThis as any).__canvasUpscale = async (input: any) => {
    graphCalls++;
    assert.equal(input.ownerScopeId, 'owner'); assert.equal(input.resolution, '2K');
    return { taskId: input.taskId, localUrl: `graph-${graphCalls}.jpg`, ownerScopeId: 'owner' };
  };
  await runNode(space, upscale);
  const graphOutput = getSpace(space).nodes.find((item: any) => item.id === upscale);
  assert.equal(graphCalls, 2, 'upscale node processes every connected batch image without a prompt');
  assert.equal(graphOutput.status, 'done'); assert.equal(graphOutput.batchOutputs.length, 2);
  assert.equal(graphOutput.output.upscaleResolution, '2K');
  assert.equal(getSpace(space).nodes.find((item: any) => item.id === node).output.url, original.url, 'upstream original is preserved');
  const { kindsAccepting } = require('./types');
  assert.ok(kindsAccepting('image').includes('imageUpscale'), 'upscale appears when adding a node from an image port');
  const { validateGraph } = require('./validation');
  validateGraph(getSpace(space).nodes, getSpace(space).edges);
  const next = api.addNode(space, 'imageGenerator', { x: 900, y: 0 });
  api.updateNode(space, next, { prompt: 'Use the upscaled image' });
  api.connect(space, { source: upscale, target: next, targetHandle: 'refs' });
  const received: string[] = [];
  (globalThis as any).__canvasGenerate = async (input: any) => {
    received.push(input.references[0].source);
    return { taskId: input.taskId, localUrl: `next-${received.length}.jpg` };
  };
  await runNode(space, next);
  assert.deepEqual(received, ['graph-1.jpg', 'graph-2.jpg'], 'downstream receives the upscaled batch');
  assert.equal(graphCalls, 2, 'downstream reuses completed upscale instead of submitting again');
  api.updateNode(space, upscale, { upscaleResolution: '4K' });
  assert.equal(getSpace(space).nodes.find((item: any) => item.id === upscale).stale, true);
  console.log('Canvas upscale: account recovery, deduplication, history, batch outputs, failure and cancellation passed.');
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
