import assert from 'node:assert/strict';

async function main() {
  const memory = new Map();
  Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { getItem: (key: string) => memory.get(key) || null, setItem: (key: string, value: string) => memory.set(key, value) } });
  const events = new Set<(task: any) => void>();
  (globalThis as any).window = { googleFlowRuntime: { onStatus: () => () => {}, onTask: (fn: any) => { events.add(fn); return () => events.delete(fn); }, getStatus: async () => ({ credentials: [{ credentialId: 'real', email: 'actual@gmail.com' }] }) } };
  const { useCanvasStore } = require('./canvas-store') as typeof import('./canvas-store');
  const { runNodes, cancelSpace, runNode, cancelNode } = require('./runner') as typeof import('./runner');
  const api = useCanvasStore.getState();
  const id = api.createSpace('Run test');
  const a = api.addNode(id, 'imageGenerator', { x: 0, y: 0 }), b = api.addNode(id, 'imageGenerator', { x: 400, y: 0 });
  api.updateNode(id, a, { prompt: 'one' }); api.updateNode(id, b, { prompt: 'two' });
  api.connect(id, { source: a, target: b, targetHandle: 'refs' });
  let calls = 0;
  (globalThis as any).__canvasGenerate = async (input: any) => {
    calls++;
    for (const listener of events) listener({ taskId: input.taskId, kind: 'image', status: 'submitting', credentialId: 'real', submittedAt: Date.now() });
    return new Promise((resolve, reject) => {
      const timeout = setTimeout(() => resolve({ taskId: input.taskId, localUrl: `result-${calls}`, credentialId: 'real' }), 30);
      input.signal.addEventListener('abort', () => { clearTimeout(timeout); reject(new DOMException('Cancelled', 'AbortError')); }, { once: true });
    });
  };
  await runNodes(id, [a, b]); assert.equal(calls, 2, 'selected dependency runs once');
  assert.equal(useCanvasStore.getState().spaces[0].nodes[0].output?.accountEmail, 'actual@gmail.com');
  calls = 0;
  await Promise.all([runNode(id, a), runNode(id, a)]); assert.equal(calls, 1, 'simultaneous clicks share execution');
  calls = 0;
  const cancelled = runNodes(id, [a, b]); cancelSpace(id);
  await assert.rejects(cancelled, { name: 'AbortError' }); assert.ok(calls <= 1);
  assert.equal(useCanvasStore.getState().spaces[0].nodes.some((node) => node.status === 'running'), false);
  const stopped = runNode(id, a); cancelNode(a); await assert.rejects(stopped, { name: 'AbortError' });
  assert.equal(events.size, 0, 'runtime subscriptions cleaned up');
  const batchSpace = api.createSpace('Batch');
  const list = api.addNode(batchSpace, 'list', { x: 0, y: 0 });
  const image = api.addNode(batchSpace, 'imageGenerator', { x: 400, y: 0 });
  const edit = api.addNode(batchSpace, 'imageEdit', { x: 800, y: 0 });
  api.updateNode(batchSpace, list, { items: ['cat', 'dog', 'bird'] });
  api.updateNode(batchSpace, edit, { prompt: '' });
  api.connect(batchSpace, { source: list, target: image, targetHandle: 'prompt' });
  api.connect(batchSpace, { source: image, target: edit, targetHandle: 'refs' });
  calls = 0; await runNode(batchSpace, edit);
  assert.equal(calls, 3, 'only upstream generation calls AI');
  assert.equal((globalThis as any).__localEdits, 3, 'all three images are processed locally');
  const batchState = () => useCanvasStore.getState().spaces.find((space) => space.id === batchSpace)!;
  assert.equal(batchState().nodes.find((node) => node.id === image)?.batchOutputs?.length, 3);
  calls = 0; await runNode(batchSpace, edit); assert.equal(calls, 0, 'local editing reuses clean upstream without AI');
  assert.equal(batchState().nodes.find((node) => node.id === edit)?.batchOutputs?.length, 3);
  api.updateNode(batchSpace, edit, { imageEdit: { crop: true, x: 0, y: 0, width: 50, height: 100, ratio: 'free', chroma: false, color: '#00ff00', threshold: 80, softness: 40 } });
  assert.equal(batchState().nodes.find((node) => node.id === edit)?.stale, true, 'edit settings invalidate output');
  api.saveTemplate(batchSpace, [list, image, edit], 'Reusable');
  const template = useCanvasStore.getState().templates[0];
  const pasted = api.pasteNodes(batchSpace, template.nodes, template.edges, 80);
  assert.equal(pasted.length, 3);
  assert.equal(batchState().nodes.find((node) => node.id === pasted[1])?.batchOutputs, undefined, 'template does not reuse generated batch');
  calls = 0; const partial = runNode(batchSpace, image);
  setTimeout(() => cancelNode(image), 45);
  await assert.rejects(partial, { name: 'AbortError' });
  assert.equal(batchState().nodes.find((node) => node.id === image)?.stale, true, 'cancelled batch cannot be reused as complete');
  assert.ok(calls < 3);
  const named = api.createSpace('Named upload');
  const local = api.addNode(named, 'localImage', { x: 0, y: 0 });
  const target = api.addNode(named, 'imageGenerator', { x: 400, y: 0 });
  api.setLocalImage(named, local, 'brand.png');
  api.updateNode(named, local, { name: 'Brand Logo' });
  api.updateNode(named, target, { prompt: `Use @{${local}} on a poster` });
  let submitted: any;
  (globalThis as any).__canvasGenerate = async (input: any) => { submitted = input; return { taskId: input.taskId, localUrl: 'named-output' }; };
  await assert.rejects(runNode(named, target), /INPUT_REQUIRED/);
  assert.equal(typeof submitted, 'undefined', 'unconnected mention must not reach the provider');
  api.connect(named, { source: local, target, targetHandle: 'refs' });
  await runNode(named, target);
  assert.equal(submitted.references[0].source, 'brand.png');
  assert.equal(submitted.references[0].fileName, 'Brand Logo');
  assert.equal(submitted.prompt, 'Use Brand Logo (reference image 1) on a poster');
  api.updateNode(named, local, { name: 'New Logo' });
  await runNode(named, target); assert.equal(submitted.references[0].fileName, 'New Logo');
  const video = api.addNode(named, 'videoGenerator', { x: 800, y: 0 });
  api.updateNode(named, video, { prompt: 'animate', model: 'Gemini_Omni_Flash', videoDuration: 10 });
  api.connect(named, { source: local, target: video, targetHandle: 'end' });
  let videoInput: any;
  (globalThis as any).__canvasGenerateVideo = async (input: any) => { videoInput = input; return { taskId: input.taskId, videoUrl: 'movie.mp4' }; };
  await assert.rejects(runNode(named, video), /VIDEO_START_REQUIRED/);
  assert.equal(typeof videoInput, 'undefined', 'end-only input must fail before provider/upload');
  api.connect(named, { source: local, target: video, targetHandle: 'start' });
  await runNode(named, video);
  assert.equal(videoInput.length, 10); assert.equal(videoInput.startImageUrl, 'brand.png');
  assert.equal(videoInput.referenceImageUrls, undefined, 'First never submits reference mode');
  const uploadedVideo = api.addNode(named, 'videoGenerator', { x: 1000, y: 0 });
  api.updateNode(named, uploadedVideo, { prompt: 'animate', refs: ['uploaded.png', 'extra.png'] });
  await runNode(named, uploadedVideo);
  assert.equal(videoInput.startImageUrl, 'uploaded.png', 'First uses the first uploaded image');
  assert.equal(videoInput.referenceImageUrls, undefined);
  api.updateNode(named, uploadedVideo, { videoMode: 'ref' });
  await runNode(named, uploadedVideo);
  assert.deepEqual(videoInput.referenceImageUrls, ['uploaded.png', 'extra.png']);
  assert.equal(videoInput.startImageUrl, undefined);
  assert.equal(videoInput.endImageUrl, undefined);
  api.connect(named, { source: local, target: uploadedVideo, targetHandle: 'start' });
  await runNode(named, uploadedVideo);
  assert.deepEqual(videoInput.referenceImageUrls, ['uploaded.png', 'extra.png', 'brand.png']);
  api.updateNode(named, uploadedVideo, { refs: ['1.png', '2.png', '3.png'] });
  await assert.rejects(runNode(named, uploadedVideo), /VIDEO_REF_INPUT_INVALID/);
  api.updateNode(named, video, { model: 'Veo_3.1-Fast' });
  await runNode(named, video); assert.equal(videoInput.length, 8, 'unsupported duration resets for actual model');
  const { videoDurations, videoDuration } = require('../lib/ai/video-duration');
  assert.deepEqual(videoDurations('Gemini Omni Flash'), [4, 6, 8, 10]);
  assert.deepEqual(videoDurations('Veo_3.1-Fast'), [4, 6, 8]);
  assert.equal(videoDuration('Gemini Omni Flash', 6), 6);
  assert.equal(videoDuration('Gemini Omni Flash'), 8);
  console.log('Selected execution, deduplication, account, cancellation and cleanup checks passed.');
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
