import assert from 'node:assert/strict';
import { generationPhase } from './progress';
const memory = new Map<string, string>();
Object.defineProperty(globalThis, 'localStorage', { value: { getItem: (key: string) => memory.get(key) ?? null, setItem: (key: string, value: string) => memory.set(key, value), removeItem: (key: string) => memory.delete(key) }, configurable: true });
const store = (require('./canvas-store') as typeof import('./canvas-store')).useCanvasStore;
const api = store.getState();
const spaceId = api.createSpace('Regression');
const source = api.addNode(spaceId, 'imageGenerator', { x: 0, y: 0 });
const target = api.addNode(spaceId, 'videoGenerator', { x: 400, y: 0 });
api.connect(spaceId, { source, target, targetHandle: 'start' });
const space = () => store.getState().spaces.find((item) => item.id === spaceId)!;
const node = (id: string) => space().nodes.find((item) => item.id === id)!;
const count = () => store.getState().undoStacks[spaceId].length;
let before = count();
api.moveNodes(spaceId, [{ id: source, position: { x: 50, y: 80 } }, { id: target, position: { x: 450, y: 80 } }]);
assert.equal(count(), before + 1);
api.undo(spaceId); assert.equal(node(source).position.x, 0); assert.equal(node(target).position.x, 400);
api.redo(spaceId); assert.equal(node(source).position.y, 80); assert.equal(node(target).position.y, 80);
api.moveNodes(spaceId, [{ id: source, position: { x: 50, y: 80 } }]); assert.equal(count(), before + 1, 'duplicate drag callbacks must be no-ops');
api.removeElements(spaceId, [source, target], space().edges.map((edge) => edge.id));
assert.equal(space().nodes.length, 0); api.undo(spaceId);
assert.equal(space().nodes.length, 2); assert.equal(space().edges.length, 1);
const output = (url: string) => ({ kind: 'image' as const, url, model: 'model', createdAt: Date.now(), prompt: url });
before = count();
api.updateNode(spaceId, source, { status: 'running', phase: 'queued' });
api.undo(spaceId); assert.equal(count(), before, 'undo disabled while running');
api.updateNode(spaceId, source, { status: 'done', output: output('first'), stale: false });
assert.equal(count(), before, 'runtime reports must not create undo steps');
api.updateNode(spaceId, source, { prompt: 'changed' });
api.updateNode(spaceId, source, { status: 'done', output: output('second'), stale: false });
api.updateNode(spaceId, target, { status: 'done', output: { ...output('video'), kind: 'video' }, stale: false });
api.undo(spaceId);
assert.equal(node(source).output?.url, 'second', 'undo prompt must preserve newly generated media');
assert.equal(node(source).outputs?.length, 2);
assert.equal(node(source).stale, true); assert.equal(node(target).stale, true);
api.selectOutput(spaceId, source, node(source).outputs![1]); assert.equal(node(source).output?.url, 'first');
api.undo(spaceId); assert.equal(node(source).output?.url, 'second');
for (let i = 0; i < 40; i++) api.updateNode(spaceId, source, { status: 'done', output: output(`result-${i}`) });
assert.equal(node(source).outputs?.length, 30);
const copies = api.pasteNodes(spaceId, space().nodes, space().edges, 60);
assert.equal(copies.length, 2); assert.equal(node(copies[0]).outputs, undefined);
api.undo(spaceId); assert.equal(space().nodes.length, 2);
const saved = JSON.parse(memory.get('video-studio-canvas')!).state;
assert.equal(saved.undoStacks, undefined); assert.equal(saved.spaces[0].nodes[0].outputs.length, 30);
console.log('Canvas regression checks passed: group move/delete, undo/redo, history, stale propagation, persistence.');

const newId = api.addNode(spaceId, 'imageGenerator', { x: 900, y: 900 });
api.updateNode(spaceId, newId, { status: 'done', output: output('preserved-on-redo') });
api.undo(spaceId); assert.equal(space().nodes.some((n) => n.id === newId), false);
api.redo(spaceId); assert.equal(node(newId).output?.url, 'preserved-on-redo');
assert.deepEqual(generationPhase({ phase: 'queued', phaseStartedAt: 100 }, { taskId: 't', kind: 'image', status: 'submitting', submittedAt: 500 }, 600), { phase: 'submitting', phaseStartedAt: 500 });
assert.deepEqual(generationPhase({ phase: 'submitting', phaseStartedAt: 500 }, { taskId: 't', kind: 'image', status: 'polling' }, 900), { phase: 'polling', phaseStartedAt: 500 });
assert.equal(generationPhase({ phase: 'polling', phaseStartedAt: 500 }, { taskId: 't', kind: 'image', status: 'polling' }, 1000), null);
assert.deepEqual(generationPhase({ phase: 'polling', phaseStartedAt: 500 }, { taskId: 't', kind: 'image', status: 'downloading' }, 1200), { phase: 'downloading', phaseStartedAt: 1200 });
console.log('Generation phase timing and generated-node redo checks passed.');

const initialHistory = count();
api.setViewport(spaceId, { x: 123, y: 456, zoom: 0.7 });
assert.deepEqual(space().viewport, { x: 123, y: 456, zoom: 0.7 }); assert.equal(count(), initialHistory);
api.groupNodes(spaceId, [source, target], 'Two nodes');
const group = space().nodes.find((node) => node.kind === 'group')!;
assert.ok(group.width! > 400); assert.equal(node(source).groupId, group.id);
const originalPosition = { ...node(source).position };
api.moveNodes(spaceId, [{ id: group.id, position: { x: group.position.x + 80, y: group.position.y + 90 } }]);
assert.equal(node(source).position.x, originalPosition.x + 80); assert.equal(node(target).groupId, group.id);
api.undo(spaceId); assert.equal(node(source).position.x, originalPosition.x);
api.ungroupNodes(spaceId, [group.id]); assert.equal(node(source).groupId, undefined);
api.undo(spaceId); assert.equal(node(source).groupId, group.id);
api.removeNode(spaceId, group.id); assert.equal(node(source).groupId, undefined);
api.undo(spaceId); assert.equal(node(source).groupId, group.id);
const importedId = api.importSpace(structuredClone(space()));
const importedSpace = store.getState().spaces.find((item) => item.id === importedId)!;
assert.notEqual(importedSpace.id, spaceId); assert.equal(importedSpace.nodes.length, space().nodes.length);
assert.ok(importedSpace.nodes.every((node) => !space().nodes.some((old) => old.id === node.id)));
console.log('Viewport, grouping, group drag/undo, import identity checks passed.');

api.updateNode(spaceId, source, { stale: false, status: 'done' });
api.updateNode(spaceId, target, { stale: false, status: 'done' });
api.updateNode(spaceId, source, { name: 'Renamed only' });
assert.equal(node(source).stale, false); assert.equal(node(target).stale, false);
const noOpHistory = count();
api.updateNode(spaceId, source, { prompt: node(source).prompt });
api.updateNode(spaceId, source, { model: node(source).model });
api.selectOutput(spaceId, source, node(source).output!);
api.addRefs(spaceId, source, []);
api.removeRef(spaceId, source, 'missing');
api.connect(spaceId, { source, target, targetHandle: 'start' });
assert.equal(count(), noOpHistory, 'unchanged inputs must not create undo entries');
assert.equal(node(source).stale, false); assert.equal(node(target).stale, false);
api.addRefs(spaceId, source, ['new-reference']);
assert.equal(node(source).stale, true); assert.equal(node(target).stale, true);
api.updateNode(spaceId, source, { stale: false, status: 'done' });
api.updateNode(spaceId, target, { stale: false, status: 'done' });
api.addRefs(spaceId, source, ['new-reference']);
assert.equal(node(source).stale, false); assert.equal(node(target).stale, false);
api.updateNode(spaceId, source, { prompt: 'An actual new prompt' });
assert.equal(node(source).stale, true); assert.equal(node(target).stale, true);
console.log('No false stale warnings for rename, unchanged input, duplicate reference or connection.');

const { expandMentions, connectedMentionNodes } = require('./mentions') as typeof import('./mentions');
const mentionSpace = api.createSpace('Mentions');
const logo = api.addNode(mentionSpace, 'localImage', { x: 0, y: 0 });
const desc = api.addNode(mentionSpace, 'text', { x: 0, y: 250 });
const generator = api.addNode(mentionSpace, 'imageGenerator', { x: 400, y: 0 });
api.setLocalImage(mentionSpace, logo, 'logo.png');
api.updateNode(mentionSpace, logo, { name: 'Brand logo' });
api.updateNode(mentionSpace, desc, { name: 'Description', prompt: 'A playful brand' });
const rawPrompt = `Use @{${logo}} with @{${desc}}`;
api.updateNode(mentionSpace, generator, { prompt: rawPrompt });
const ms = () => store.getState().spaces.find((s) => s.id === mentionSpace)!;
assert.equal(ms().edges.length, 0, 'typing a mention must not create an input');
assert.deepEqual(connectedMentionNodes(ms().nodes, ms().edges, generator), []);
api.connect(mentionSpace, { source: logo, target: generator, targetHandle: 'refs' });
assert.deepEqual(connectedMentionNodes(ms().nodes, ms().edges, generator).map((n) => n.id), [logo], 'unconnected text must not appear in @');
api.connect(mentionSpace, { source: desc, target: generator, targetHandle: 'prompt' });
assert.equal(ms().edges.length, 2);
assert.equal(expandMentions(rawPrompt, ms().nodes, ms().edges, ['other.png', 'logo.png']), 'Use Brand logo (reference image 2) with Description: A playful brand');
api.updateNode(mentionSpace, logo, { name: 'New logo' });
assert.equal(ms().nodes.find((n) => n.id === generator)!.prompt, rawPrompt);
assert.ok(expandMentions(rawPrompt, ms().nodes, ms().edges, ['logo.png']).includes('New logo'));
assert.deepEqual(connectedMentionNodes(ms().nodes, ms().edges, logo), [], 'outgoing wires are not inputs');
const mentionCopy = api.importSpace(structuredClone(ms()));
const copiedMentionSpace = store.getState().spaces.find((s) => s.id === mentionCopy)!;
const copiedPrompt = copiedMentionSpace.nodes.find((n) => n.kind === 'imageGenerator')!.prompt;
assert.ok(!copiedPrompt.includes(logo));
assert.ok(expandMentions(copiedPrompt, copiedMentionSpace.nodes, copiedMentionSpace.edges, ['logo.png']).includes('New logo'));
api.updateNode(mentionSpace, generator, { prompt: `Use @{${logo}}` });
assert.equal(ms().edges.length, 2, 'deleting a mention must retain existing wires');
api.undo(mentionSpace); assert.equal(ms().edges.length, 2);
api.disconnect(mentionSpace, ms().edges.find((e) => e.source === logo)!.id);
assert.deepEqual(connectedMentionNodes(ms().nodes, ms().edges, generator).map((n) => n.id), [desc]);
const isolatedCopy = api.pasteNodes(mentionSpace, [ms().nodes.find((n) => n.id === generator)!], [], 80)[0];
assert.deepEqual(connectedMentionNodes(ms().nodes, ms().edges, isolatedCopy), [], 'pasting a prompt must not create wires');
assert.ok(!ms().nodes.find((n) => n.id === generator)!.prompt.includes(`@{${logo}}`));
assert.throws(() => expandMentions('@{node_missing}', ms().nodes, ms().edges, []), /INPUT_REQUIRED/);
console.log('Mentions: wiring, expansion, rename, import ID remap, removal and undo passed.');

const refSpace = api.createSpace('Video Ref multi-wire');
const refVideo = api.addNode(refSpace, 'videoGenerator', { x: 400, y: 0 });
const refSources = [0, 1, 2].map((y) => api.addNode(refSpace, 'localImage', { x: 0, y: y * 200 }));
const refGraph = () => store.getState().spaces.find((s) => s.id === refSpace)!;
api.updateNode(refSpace, refVideo, { videoMode: 'ref' });
for (const source of refSources) api.connect(refSpace, { source, target: refVideo, targetHandle: 'start' });
assert.deepEqual(refGraph().edges.map((e) => e.source), refSources, 'Ref retains all three wires on the same image input');
api.connect(refSpace, { source: refSources[0], target: refVideo, targetHandle: 'start' });
assert.equal(refGraph().edges.length, 3, 'reconnecting the same source does not duplicate it');
const importedRef = api.importSpace(structuredClone(refGraph()));
assert.equal(store.getState().spaces.find((s) => s.id === importedRef)!.edges.length, 3, 'Ref multi-wires survive import validation');
api.updateNode(refSpace, refVideo, { videoMode: 'first' });
const replacement = api.addNode(refSpace, 'localImage', { x: 0, y: 600 });
api.connect(refSpace, { source: replacement, target: refVideo, targetHandle: 'start' });
assert.deepEqual(refGraph().edges.map((e) => e.source), [replacement], 'First still replaces the start frame');
api.undo(refSpace);
assert.equal(refGraph().edges.length, 3, 'undo restores replaced wires');
console.log('Video ports: Ref multi-wire, duplicate prevention, import, First replacement and undo passed.');
